app/__init__.py
from flask import Flask
import os
import ConfigParser
from logging.handlers import RotatingFileHandler
from flask.ext.pymongo import PyMongo
from flask.ext.cors import CORS
from app.utils.mongo_utils import MongoUtils

# Create MongoDB database object.
mongo = PyMongo()

#Initialize mongo access point
mongo_utils = MongoUtils(mongo)

def create_app():
    # Here we  create flask instance
    app = Flask(__name__)

    # Allow cross-domain access to API.
    #cors = CORS(app, resources={r"/api/*": {"origins": "*"}})

    # Load application configurations
    load_config(app)

    # Configure logging.
    configure_logging(app)

    # Init modules
    init_modules(app)

    # Initialize the app to work with MongoDB
    mongo.init_app(app, config_prefix='MONGO')

    return app


def load_config(app):
    ''' Reads the config file and loads configuration properties into the Flask app.
    :param app: The Flask app object.
    '''
    # Get the path to the application directory, that's where the config file resides.
    par_dir = os.path.join(__file__, os.pardir)
    par_dir_abs_path = os.path.abspath(par_dir)
    app_dir = os.path.dirname(par_dir_abs_path)

    # Read config file
    config = ConfigParser.RawConfigParser()
    config_filepath = app_dir + '/config.cfg'
    config.read(config_filepath)

    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
    app.config['MONGO_DBNAME'] = config.get('Mongo', 'DB_NAME')

    # Logging path might be relative or starts from the root.
    # If it's relative then be sure to prepend the path with the application's root directory path.
    log_path = config.get('Logging', 'PATH')
    if log_path.startswith('/'):
        app.config['LOG_PATH'] = log_path
    else:
        app.config['LOG_PATH'] = app_dir + '/' + log_path

    app.config['LOG_LEVEL'] = config.get('Logging', 'LEVEL').upper()


def configure_logging(app):
    ''' Configure the app's logging.
     param app: The Flask app object
    '''

    log_path = app.config['LOG_PATH']
    log_level = app.config['LOG_LEVEL']

    # If path directory doesn't exist, create it.
    log_dir = os.path.dirname(log_path)
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    # Create and register the log file handler.
    log_handler = RotatingFileHandler(log_path, maxBytes=250000, backupCount=5)
    log_handler.setLevel(log_level)
    app.logger.addHandler(log_handler)

    # First log informs where we are logging to.
    # Bit silly but serves  as a confirmation that logging works.
    app.logger.info('Logging to: %s', log_path)


def init_modules(app):

    # Import blueprint modules
    from app.mod_main.views import mod_main

    app.register_blueprint(mod_main)

app/mod_main/views.py
from flask import Blueprint , render_template , request , redirect , url_for
from bson import json_util , ObjectId
from app import mongo
from arkep import MyForm

mod_main = Blueprint('main', __name__)


@mod_main.route ('/' ,methods=['GET' , 'POST'])
def index():
       
   db = mongo.db.arkep

   if request.method == 'GET':
        return render_template("techstitution.html")
   elif request.method =='POST':
        data = request.form.to_dict()
        db.insert(data)
        return render_template("pranimimesukses.html")
        #return json_util.dumps(data)
   else:
        return 'bad request'
    

@mod_main.route('/<string:id>', methods=['GET'])
def get_doc(id):
    db = mongo.db.arkep
    
    if request.method == 'GET':
        doc = db.find_one({"_id":ObjectId(id)})
        doc_json = json_util.dumps(doc)
        return render_template('doc.html', doc=doc)
    else:
        return "bad request"
    
    
@mod_main.route('/remove/<string:id>', methods=['GET'])
def remove_doc(id):
    db = mongo.db.arkep
    if request.method == 'GET':
        doc = db.remove({"_id":ObjectId(id)})
        return redirect(url_for('main.lista'))
    else:
        return "bat request"
    
@mod_main.route('/lista' , methods=['GET'])
def lista():
    dokumentat = mongo.db.arkep.find()
    return render_template('lista.html' , documentat = dokumentat)

app/templates/doc.html
{% extends 'layout.html' %}

{% block content%}

Rezultati i kerkuar:

{{ doc }}
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>

        <title>ARKEP-Formulari</title>
      <link rel="icon" type="image/png" href="../static/ark.png"> 
      <meta charset="utf-8">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

       <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/jquery.validate.min.js"></script>    
       
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/additional-methods.js"></script>
              
                  <link rel="stylesheet" href="{{url_for( 'static', filename='ul.css') }}">
	<link rel="stylesheet" href="{{url_for( 'static', filename='button.css') }}">
                  <link rel="stylesheet" href="{{url_for( 'static', filename='input.css') }}">
                  <link rel="stylesheet" href="{{url_for( 'static', filename='b.css') }}">

</head>
<body style="background-color:#e4e4e4;">
{% block header %}

{% endblock %}

<br>

{% block content %}


{% endblock %}


<br>

<footer>
 <ul style="width:100%;text-align:center;">
      <br>

   <b class="b28"> Adresa:Qyteza Pejton, Rr. Mujo Ulqinaku nr. 7, 10 000 Prishtine, Republika e Kosoves</b>
       <br>

     <img src="../static/email.png" class="b29"> </img>
     <b class="b30"> info@arkep-rks.org </b>

     <img src="../static/phone.png" class="b31"> </img>
     <b class="b30">  + 381 (38) 212-345;</b>

           <br><br>
      <img src="../static/printer.png" class="b32"> </img>
      <b class="b33"> + 381 (38) 212 399;</b>

      <img src="../static/www.png" class="b34"> </img>
      <b class="b35"> www.arkep-rks.org</b><br>

   </ul>
 </footer>

</body>
</html>

app/templates/lista.html
{% extends 'layout.html' %}
{% block header %} 
<h1 style="margin-left:10%;font-weight:bold;">Kompania</h1>
{% endblock %}
{% block content%}

<fieldset id="fieldset"> <table  id="tabela">
<tr>
<td id="h"><b>Emri i Ndermarresit<b></td>
<td id="h"><b>Adresa<b></td>
<td id="h"><b>Opsionet<b></td>
</tr>
<tbody>
{% for item in documentat %}
<tr>
<td>{{ item['emri_i_ndermaresit'] }}</td>
<td>{{ item['adresa'] }}</td>
<td>
<a href="{{url_for('main.get_doc',id=item._id)}}">View&nbsp;</a>
<a href="{{url_for('main.remove_doc',id=item._id)}}">Delete</a>
</td>
</tr>
{% endfor %}
</tbody>
</table>
</fieldset>
{% endblock %}
 {%endfor%}
{% endblock %}

app/templates/pranimimesukses.html
<html>
<body>
<ul >
   <li >
       <img src="../static/arkep2.png" style="margin-left:6px;margin-top:-5px;margin-right:2px;"></img>
   </li>
  
   <li >
      <img src="../static/ARKEP3.png" style="cursor:default;margin-left:6px;margin-top:-6%;margin-right:2px;"></img>
   </li>
  
   <li style="cursor:pointer;float:right;font-size:20px;margin-right:3%;margin-top:-1%;">
         <a href="http://www.arkep-rks.org/">
        <img src="../static/home.png" style="margin-left:-4px;margin-top:-7px;margin-right:3px;"></img>Home
        </a>
   </li>
</ul>

<p> Te dhenat e juaja jane derguar me sukses ! </p>



</body>


app/templates/techstitution1.html
{% extends "layout.hmtl" %}

{% block header %}

<ul >
   <li >
       <img src="../static/arkep2.png" style="margin-left:6px;margin-top:-5px;margin-right:2px;"></img>
   </li>
  
   <li >
      <img src="../static/ARKEP3.png" style="cursor:default;margin-left:6px;margin-top:-6%;margin-right:2px;"></img>
   </li>
  
   <li style="cursor:pointer;float:right;font-size:20px;margin-right:3%;margin-top:-1%;">
         <a href="http://www.arkep-rks.org/">
        <img src="../static/home.png" style="margin-left:-4px;margin-top:-7px;margin-right:3px;"></img>Home
        </a>
   </li>
</ul>
  
<h1 class="a1">Formular Njoftimi</h1>

     <p class="a2">Hyrje ne aktivitetin e Komunikimeve Elektronike</p>
             <br>
 
     <p class="a3">
        Autoriteti do te procedoj me shqyrtimin e Formularit te Njoftimit vete pas kompletimit te Dosjes dhe do ta njoftoj ndermarresin per 
        <br> vendosjen n&euml Regjistrin e Njoftimit brenda 5 (pes&euml) dit&eumlve t&euml pun&eumls nga data e kompletimit t&euml Njoftimit. 
     </p>

     <p class="a4"> 
           * Operatoret te Licencuar sipas Ligjit per Telekomunikacion Nr.2002/7 nuk jane te obliguar qe te plotesojne piken I, V dhe VI te Formularit te Njoftimit. 
      </p>

{% endblock %}

{% block content %}

<script>
   $(document).ready(function() {
         $('#arkep').validate({
             rules: {
               emri_i_ndermaresit: {
                 required: true
               },
               numri_i_regjistrimit: {
                 required: true,
                 number: true,
                 minlength: 7
               },
               numri_fiskal: {
                 required: true
               }
             messages: {
               emri_i_ndermaresit: {
                 required: "Shkruani nje emer"
               }
               numri_i_regjistrimit: {
                 required: "Ju lutem shkruani numrat!"
               }
             }
         });
   });
  </script>


<form id="arkep" method="post">
    <p class="b2" >I. QELLIMI I NJOFTIMIT </p><br>
       
      <input type="radio" name="qellimi" value="fillim sherbimi" class="b18"> <b class="b20" >Fillimi i Sherbimit &nbsp &nbsp</b>
      <input type="radio" name="qellimi" value="shtim sherbimi" > <b class="b20"> Shtimi i Sherbimit  &nbsp &nbsp</b>
      <input type="radio" name="qellimi" value="heqje sherbimi">  <b class="b20"> Heqje e Sherbimit  </b>
                      <br>

  <p class="b1"> II.TE DHENAT PER NDERMARRESIN:</p>
        
       <b class="b10" >2.1 Emri i Ndermarresit (Entiteti)   </b>
            <input type="text" name="emri_i_ndermaresit" id="emri_i_ndermaresit"  class="a5"><br>

       <b class="b3">2.2 Numri i Regjistrimit te Biznesit &nbsp&nbsp</b>
            <input type="text" name="numri_i_regjistrimit" id="numri_i_regjistrimit"  class="a5" ><br>

       <b class="b4">2.3 Numri fiskal &nbsp&nbsp</b>
            <input type="text" name="numri_fiskal" id="numri_fiskal"  class="a5" ><br>

       <b class="b5">2.4  Adresa  &nbsp &nbsp</b>
             <input type="text" name="adresa"  class="a5" ><br> 
          
       <b class="b6">2.5 Numri i Telefonit &nbsp </b>
              <input type="text" name="numri i telefonit"  class="a5" ><br>
   
       <b class="b7">2.6 Numri i Faksit &nbsp&nbsp</b>
              <input type="text" name="numri i faksit"  class="a5" ><br>

       <b class="b3">2.7 Email Adresa </b>
               <input type="email" name="email"  class="a5" >


  
   <p class="b1">III. TE DHENAT PER ZYRTARIN LIGJERISHT TE PERGJEGJESHEM:  </p><br>
      
         <b class="b8">3.1 Emri i Zyrtarit </b>
                  <input type="text" name="emri i zyrtarit"  class="a5" ><br>
         
         <b class="b9">3.2 Adresa &nbsp</b>
                  <input type="text" name="adresa e zyrtarit"  class="a5" ><br>
         
         <b class="b10">3.3 Numri i Telefonit </b>
                   <input type="text" name="numri i zyrtarit"  class="a5" ><br>
        
          <b class="b8">3.4 Numri i Faksit </b>
                   <input type="text" name="fax"  style="a5" ><br>
         
          <b class="b8">3.5 E-mail Adresa </b>
                   <input type="email" name="adresa email"  class="a5" ><br>
         
          <b class="b11">3.6 Nr. I ID-se </b>
                    <input type="text" name="ID"  class="a5" >



   
   <p class="b1">IV. AKTIVITETET TE CILAT NJOFTOHEN/CREGJISTROHEN:  </p><br> 
                
            <b class="b12" >4.1 Ofrimi i rrejtit publik fiks:</b><br>
                    <input type="radio" name="lloji"     class="b14"  >  <b class="b13"> Lokal       </b><br>
                    <input type="radio" name="lloji"     class="b14"  >  <b class="b13"> Nacional </b><br>
                    <input type="radio" name="lloji"     class="b14"  >  <b class="b13"> Te tjera   </b><br>
                         <b class="b15">Nese keni zgjedhur te tjera ju lutem specifikoni: </b><br>
                                  <textarea name="rrjetipubl"   rows="10" cols="20" class="b16" ></textarea>
                                        <br><br>


           <b class="b12">4.2 Ofrimi i sherbimeve publike fikse:</b><br>
                     <input type="radio" name="Sherbimet"    class="b17"><b class="b19"> Sherbime telefonike lokale/nacionale</b><br>
                     <input type="radio" name="Sherbimet"    class="b18"><b class="b20"> Sherbime telefonike nderkombetare</b><br>
                     <input type="radio" name="Sherbimet"    class="b18"><b class="b20"> Telefona publik me pagese</b><br>
                     <input type="radio" name="Sherbimet"    class="b18"><b class="b20"> Sherbime tjera</b><br>
                           <b class="b15">Nese keni zgjedhur sherbime te tjera ju lutem tregoni ato: </b><br>
                                <textarea name="sherbimipubl"   rows="10" cols="20" class="b16"></textarea>
                                        <br><br>   

          <b class="b12">4.3 Ofrimi i rrjetit publik mobil:</b><br>
                    <input type="radio" name="mobile" class="b17"><b class="b19"> Lokal</b><br>
                    <input type="radio" name="mobile" class="b18"><b class="b20"> Nacional</b>
                                         <br><br>
      
         <b class="b12">4.4 Ofrimi i sherbimeve publike mobile:</b><br>
               <input type="radio" name="transmentime" class="b17"><b class="b19"> Sherbime telefonike te zerit</b><br>
               <input type="radio" name="transmentime" class="b18"><b class="b20"> Transmetim te dhenash</b>
                                         <br><br>
     
        <b class="b12">4.5 Ofrimi i sherbimeve te linjave me qira:</b><br>
               <input type="radio" name="linja" class="b17"><b class="b19"> Fiber optik te pa-ndricuar</b><br>
               <input type="radio" name="linja" class="b18"><b class="b20"> Linja tjera me qira</b>
                                         <br><br>  

        <b class="b12">4.6 Ofrimi i rrjetave publike me transmetim satelitor:</b><br>
                  <input type="radio" name="rrjeta" class="b17">
                     <b class="b19"> Ofrimi i rrjetave publike me transmetim satelitor</b>
                                    <br><br> 

        <b class="b12">4.7 Ofrimi i sherbimeve publike satelitore:</b><br>
                 <input type="radio" name="satelite" class="b17"><b class="b19"> Ofrimi i sherbimeve publike satelitore</b>
                                    <br><br>

        <b class="b12">4.8 Ofrimi i sherbimeve te transmetimit te te dhenave (Internetit):</b><br>
                 <input type="radio" name="internet" class="b17">
                       <b class="b19"> Ofrimi i sherbimeve te transmetimit te te dhenave (Internetit)</b>
                                     <br><br>

        <b class="b12">4.9 Ofrimi i sherbimeve me vlere te shtuar:</b><br>
                 <input type="radio" name="sherbimemevler" class="b17">
                        <b class="b19"> Ofrimi i sherbimeve me vlere te shtuar</b>
                                     <br>



   <p class="b1">V.PERSHKRIMI I AKTIVITETIT DHE FAZA E OFRIMIT:  </p> <br>

       <b class="b12">5.1 Pershkrimi i rrjetit dhe/ose sherbimit qe do te ofrohet:  </b>
                  <p class="b2" >(Te jepen pershkrime te detajuara per secilin aktivitet te njoftuar duke specifikuar:  </p> 
                  <p class="b2"> &middot A do te perdoret rrjeti vetanak apo ndonje rrjet tjeter, </p> 
                  <p class="b2">  &middot Teknologjia e cila do te perdoret,                                    </p>
                  <p class="b2">  &middot Radio frekuencat, te cilat planifikohen te perdoren,     </p>
                  <p class="b2">  &middot Lista e sherbimeve qe planifikohen te ofrohen,             </p>
                  <p class="b2"> &middot Etj.)     </p>
                       <textarea name="pershkrimsherbimi"  placeholder="Jep pershkrimin ..." rows="10" cols="20" class="b16" ></textarea>
                                <br><br>

        <b class="b12">5.2 Faza e Ofrimit:</b><br>
                  <p class="b2">(Te specifikohet koha e parashikuar per fillimin e aktivitetit te komunikimeve elektronike)</p>
                       <textarea name="fazaeofrimit"  placeholder="Shkruaj ketu ..." rows="10" cols="20" class="b16" ></textarea>
                                        <br><br>



    <p class="b1">VI.DOKUMENTET E BASHKANGJITURA:  </p><br>


         <b class="b12">6.1 Dokumentet e bashkangjitura si shtojce aplikacionit te Njoftimit</b>
                 <p class="b21"> 1.Kopje e certifikates se regjistrimit te biznesit</p>
                 <p class="b22">2.Kopje e Certifikates se numrit fiskal</p>
                 <p class="b22">3.Kopje e dokumentit 'Informate mbi biznesin</p>
                            <input type="file" id="myFile" class="b23" >
                            <input type="file" id="myFile" class="b23" >
                            <input type="file" id="myFile" class="b23" >
                                   <br><br>



   <p class="b1">VII.KONFIRMIMI I NJOFTIMIT:  </p><br>

          <b class="b12">7.1 Ndermarrja kerkon qe t'i leshohet certifikata e konfirmimit te njoftimit per ofrimin e rrjeteve dhe/ose sherbimeve publike te 
          <p class="b12"> komunikimeve elektronike te njoftuara permes ketij formulari: </p></b>
                  <input type="radio" name="zgjedhja" class="b24"> <b class="b20"> Po </b><br>
                  <input type="radio" name="zgjedhja" class="b18"> <b class="b20"> Jo  </b>
                                 <br>



   <p class="b1">VIII. DETYRIMET LIGJORE:  </p><br>

       <input type="radio" name="1" class="b18"><b class="b25">Une nepermjet ketij dokumenti deklaroj se do te ushtroj aktivitet ne fushen e komunikimeve elektronike te shenuara me siper dhe aplikoj <br>
                  <b class="b26">per regjistrim ne regjistrin e ofrueseve te rrjeteve dhe sherbimeve te komunikimeve elektronike te Autoritetit (ARKEP).</b></b><br>
    
       <input type="radio" name="1" class="b18"><b class="b25">Une nepermjet ketij dokumenti deklaroj se kam mbyllur aktivitetet e komunikimeve elektronike te shenuara me siper.</b><br>
       
      
       <input type="radio" name="1" class="b18"><b class="b25">Une nepermjet ketij dokumenti deklaroj se kam mbyllur cdo aktivitet te komunikimeve elektronike nen regjimin e Autorizimit te<br>
                 <b class="b26"> pergjithshem.</b></b><br>
     
       <input type="radio" name="1" class="b18"><b class="b25">Une nepermjet ketij dokumenti deklaroj se te dhenat e mia kane pesuar ndryshime, sikurse pershkruhen ne formular.</b><br>

      <input type="radio" name="1" class="b18"><b class="b25">Une nepermjet ketij dokumenti deklaroj se kam ndryshuar formen ligjore te ndermarrjes si me sic pershkruhet ne formular.<br> 
                 <b class="b26">Emri i vjeter eshte si me poshte;</b></b>
                                     <br><br>


       <p class="b27"> Une nepermjet ketij dokumenti paraqes ne ARKEP te gjithe dokumentacionin e nevojshem ligjor dhe/ose te gjithe dokumentet qe sigurojne se nenshkruesi i ketij Njoftimi Regjistrimi ka lidhje me personin perfaqesues.</p>
       <p class="b27">Une deklaroj se informacioni qe perfshihet ne deklarimin e paraqitur, sikurse cdo informacion tjeter shoqerues , eshte i sakte dhe i vertete, dhe jam plotesisht i vetedijshem per faktin qe, lidhur me angazhimin ne cdo aktivitet 
              te komunikimeve elektronike per te cilin eshte e nevojshme te sigurosh te drejten e perdorimit per numeracion dhe frekuenca, te drejta te cilat nuk sigurohen nepermjet kesaj procedure, une duhet te paraqes nje aplikim per te fituar te drejtat e
              perdorimit te cituara me siper perpara fillimit te ofrimit te sherbimit.</p>
                          <br><br> 

   <input  type="reset" value="Reset" >
   <input type="submit" value="Submit" >
</form>


<script>
function myFunction() {
    var x = document.getElementById("myFile");
    x.disabled = true;
}
</script>

{% endblock %}